name: Belgian Football Fantasy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check code
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      run: dotnet restore Api/src/BelgianFootballFantasy.Web/BelgianFootballFantasy.Web.csproj

    - name: Build Application
      run: dotnet build Api/src/BelgianFootballFantasy.Web/BelgianFootballFantasy.Web.csproj --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test Api/tests/BelgianFootballFantasy.UnitTests/BelgianFootballFantasy.UnitTests.csproj --configuration Release
